[package]
name = "project_0001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13"
serde_json = "1.0"

[dependencies.tokio]
version = "0.2"
features = ["full"]